### ISSUE TITLE
Use anchors to allow linking directly to operations/challenges

### ISSUE THREAD

**Issue by ldruschk** [ENOFLAG/ChallengePad#8]
When selecting a new operation or challenge update the anchor in the URL accordingly and upon opening the website select the operation and challenge accordingly

**Comment by Trolldemorted** [comment]
Something like `/o/Stay~/exoplanet`?

**Comment by ldruschk** [comment]
I was thinking more like `#stay~,exoplanet` but I am not sure if using the fragment identifier (which apparently is what the part after `#` is called) is better or worse, so as long as it works I don't care

**Comment by Trolldemorted** [comment]
I suppose real urls work better, because they play nicely with blazor's routing and the user agents' history.

We have [built a poc](https://github.com/ENOFLAG/ChallengePad/tree/routing), but it looks like we ran into a [blazor bug on firefox](https://github.com/dotnet/aspnetcore/issues/21002), which stops the back button from working in firefox. Apart from that there are no more major todos except writing some css to make the frontend look great again.

**Comment by ldruschk** [comment]
Well, the CodiMD OAuth2 login in Firefox is still broken, so Firefox users should be used to the ChallengePad not working properly :D

**Comment by Trolldemorted** [comment]
I am using firefox, and the oauth2 login works fine (?)
